image: gitpod/workspace-python
tasks:
  - before: |
      DISTRO=foxy && sudo apt update && sudo apt install -y curl gnupg lsb-release software-properties-common && sudo add-apt-repository universe && \
      sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null && \
      sudo apt update && sudo apt upgrade && sudo apt install -y ros-${DISTRO}-ros-base python3-argcomplete ros-dev-tools && \
      echo "source /opt/ros/${DISTRO}/setup.bash" >> ~/.bashrc && \
      echo "source /workspace/ros2-template/install/setup.bash" >> ~/.bashrc && \
      source ~/.bashrc && sudo apt install -y python3-colcon-common-extensions && colcon build